version: 2.1
jobs:
  buildProject:
    docker:
      - image: circleci/openjdk:11-jdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: first steps
          command: |
            gradle build
            pwd
            ls -al
  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: deploy master to heroku
          command: |
            git push https://heroku:e7fbfedf-75a9-4041-af0d-df9613ad31fd@git.heroku.com/circlecianswer.git master
  oscheck:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - run:
          name: just a test
          command: |
            pwd
            ls -al

workflows:
  version: 2
  build-deploy:
    jobs:
      - buildProject
      - deploy:
          requires:
            - buildProject
          filters:
            branches:
              only: master
